# Generated by Django 3.1.3 on 2020-11-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('stock', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('armazon', models.BooleanField(default=False)),
                ('lente', models.BooleanField(default=False)),
                ('lado', models.CharField(blank=True, choices=[('izquierdo', 'Izquierdo'), ('derecho', 'Derecho')], default='izquierdo', max_length=10, null=True)),
                ('distancia', models.CharField(blank=True, choices=[('lejos', 'Lejos'), ('cerca', 'Cerca')], default='lejos', max_length=5, null=True)),
            ],
        ),
    ]
