# Generated by Django 3.1.3 on 2020-12-01 04:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='distancia',
            field=models.CharField(blank=True, choices=[('lejos', 'lejos'), ('cerca', 'cerca')], default='lejos', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='lado',
            field=models.CharField(blank=True, choices=[('izquierdo', 'izquierdo'), ('derecho', 'derecho')], default='izquierdo', max_length=10, null=True),
        ),
    ]
