# Generated by Django 3.1.3 on 2020-12-01 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20201201_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
